//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile.Metrics.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mobile.Metrics.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier comporte un grand nombre de lignes de code ({0} lignes).
        /// </summary>
        internal static string Warning_File_HighNumberOfLines_Message {
            get {
                return ResourceManager.GetString("Warning_File_HighNumberOfLines_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La création d&apos;autres types permet de réduire le nombre de ligne total..
        /// </summary>
        internal static string Warning_File_HighNumberOfLines_WorkAround {
            get {
                return ResourceManager.GetString("Warning_File_HighNumberOfLines_WorkAround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier de ressource a une taille élevée ({0} kb)..
        /// </summary>
        internal static string Warning_File_HighSize_Message {
            get {
                return ResourceManager.GetString("Warning_File_HighSize_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compresser d&apos;avantage le fichier peut réduire son poids..
        /// </summary>
        internal static string Warning_File_HighSize_WorkAround {
            get {
                return ResourceManager.GetString("Warning_File_HighSize_WorkAround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier comporte un faible pourcentage de commentaires ({0:0.00}%).
        /// </summary>
        internal static string Warning_File_LowAmountOfComments_Message {
            get {
                return ResourceManager.GetString("Warning_File_LowAmountOfComments_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documenter d&apos;avantage les api publiques, commenter les algorithmes complexes..
        /// </summary>
        internal static string Warning_File_LowAmountOfComments_WorkAround {
            get {
                return ResourceManager.GetString("Warning_File_LowAmountOfComments_WorkAround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La méthode comporte une complexité cyclomatique élevée ({0}).
        /// </summary>
        internal static string Warning_Method_HighCyclomaticComplexity_Message {
            get {
                return ResourceManager.GetString("Warning_Method_HighCyclomaticComplexity_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Découper la méthode en plusieurs méthodes pour réduire la complexité cyclomatique de cette dernière..
        /// </summary>
        internal static string Warning_Method_HighCyclomaticComplexity_WorkAround {
            get {
                return ResourceManager.GetString("Warning_Method_HighCyclomaticComplexity_WorkAround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solution comporte un nombre élevé de portions de code dupliquées..
        /// </summary>
        internal static string Warning_Solution_Duplication_Message {
            get {
                return ResourceManager.GetString("Warning_Solution_Duplication_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutualiser les portions de code en créeant des types et méthodes supplémentaires..
        /// </summary>
        internal static string Warning_Solution_Duplication_WorkAround {
            get {
                return ResourceManager.GetString("Warning_Solution_Duplication_WorkAround", resourceCulture);
            }
        }
    }
}
